import XCTest

@testable import CCBuddy

/// A session's name is the only thing distinguishing it in a list of a thousand, so the rules for
/// picking one are pinned here. Every case below was observed in a real library.
final class SessionTitleTests: XCTestCase {
    private func userMessage(_ blocks: [HistoryContentBlock]) -> HistoryMessage {
        HistoryMessage(role: "user", content: blocks)
    }

    private func text(_ value: String) -> HistoryContentBlock {
        HistoryContentBlock(type: "text", text: value)
    }

    func testTitleComesFromTypedProseNotFromCarriedToolOutput() {
        // A `user` turn also carries the previous assistant turn's tool results. Naming the session
        // after those produced titles like `Script completed Wall time 1.8 seconds Output: {…}`.
        let toolResult = HistoryContentBlock(
            type: "tool_result",
            toolUseID: "call-1",
            content: .string(#"Script completed Wall time 1.8 seconds Output: {"plan":{},"goal":{}}"#)
        )
        let messages = [
            userMessage([toolResult]),
            userMessage([text("把索引限制从 600 提到全量")]),
        ]
        XCTAssertEqual(
            HistoryParsingSupport.firstUserTitle(in: messages),
            "把索引限制从 600 提到全量"
        )
    }

    func testToolCallsAreAlsoIgnored() {
        let toolUse = HistoryContentBlock(
            type: "tool_use",
            name: "Bash",
            input: .object(["command": .string("ls -la")])
        )
        let messages = [userMessage([toolUse]), userMessage([text("Rename the sidebar")])]
        XCTAssertEqual(HistoryParsingSupport.firstUserTitle(in: messages), "Rename the sidebar")
    }

    func testAnAttachmentOnlyTurnIsNotATitle() {
        // `[Image] [Image] [Image #1][Image #2]…` is a real title in the current library.
        let messages = [
            userMessage([text("[Image] [Image] [Image #1][Image #2]")]),
            userMessage([text("这两张截图里的间距对不上")]),
        ]
        XCTAssertEqual(
            HistoryParsingSupport.firstUserTitle(in: messages),
            "这两张截图里的间距对不上"
        )
    }

    func testProseSurvivesAlongsideAnAttachment() {
        let messages = [userMessage([text("[Image] 看看这个布局")])]
        XCTAssertEqual(HistoryParsingSupport.firstUserTitle(in: messages), "[Image] 看看这个布局")
    }

    func testAnIdentifierEchoedAsTextIsNotATitle() {
        let messages = [
            userMessage([text("432c1120-3875-4607-9c81-945d456a0f21")]),
            userMessage([text("continue the refactor")]),
        ]
        XCTAssertEqual(HistoryParsingSupport.firstUserTitle(in: messages), "continue the refactor")
    }

    func testBareIdentifierDetectionIsExact() {
        XCTAssertTrue(
            HistoryParsingSupport.isBareIdentifier("432c1120-3875-4607-9c81-945d456a0f21")
        )
        XCTAssertFalse(
            HistoryParsingSupport.isBareIdentifier("fix 432c1120-3875-4607-9c81-945d456a0f21"),
            "an identifier mentioned inside a sentence is still a usable title"
        )
        XCTAssertFalse(HistoryParsingSupport.isBareIdentifier("not-a-uuid"))
    }

    func testInterruptionAndCaveatNoticesAreSkipped() {
        let messages = [
            userMessage([text("[Request interrupted by user]")]),
            userMessage([text("Caveat: the messages below were generated by a hook")]),
            userMessage([text("actually let's start over")]),
        ]
        XCTAssertEqual(HistoryParsingSupport.firstUserTitle(in: messages), "actually let's start over")
    }

    func testWhitespaceIsCollapsedAndTheTitleIsBounded() {
        let long = String(repeating: "字", count: 200)
        let messages = [userMessage([text("first\n\n   second   \(long)")])]
        let title = HistoryParsingSupport.firstUserTitle(in: messages)
        XCTAssertTrue(title.hasPrefix("first second "))
        XCTAssertEqual(title.count, 90)
    }

    func testASessionWithNothingButToolTrafficHasNoTitle() {
        // Better an explicit "untitled" row than a row named after a JSON blob.
        let messages = [
            userMessage([HistoryContentBlock(type: "tool_result", content: .string("{}"))]),
        ]
        XCTAssertEqual(HistoryParsingSupport.firstUserTitle(in: messages), "")
    }
}
